export enum FieldAcervoEnum {
  Titulo = 1,
  Tombo = 2,
  Credito = 3,
  Localizacao = 4,
  Procedencia = 5,
  DataAcervo = 6,
  CopiaDigital = 7,
  AutorizacaoUsoImagem = 8,
  EstadoConservacao = 9,
  Descricao = 10,
  Quantidade = 11,
  DimensaoLargura = 12,
  DimensaoAltura = 13,
  Suporte = 14,
  FormatoImagem = 15,
  TamanhoArquivo = 16,
  Cromia = 17,
  Resolucao = 18,
  Anexos = 19,
  Tecnica = 20,
  DimensaoDiametro = 21,
}
