export enum FieldAcervoEnum {
  Titulo = 1,
  Tombo = 2,
  Credito = 3,
  Localizacao = 4,
  Procedencia = 5,
  DataAcervo = 6,
  CopiaDigital = 7,
  AutorizacaoUsoImagem = 8,
  EstadoConservacao = 9,
  Descricao = 10,
  Quantidade = 11,
  DimensaoLargura = 12,
  DimensaoAltura = 13,
  Suporte = 14,
  FormatoImagem = 15,
  TamanhoArquivo = 16,
  Cromia = 17,
  Resolucao = 18,
  Anexos = 19,
  Tecnica = 20,
  DimensaoDiametro = 21,
  DimensaoProfundidade = 22,
  Duracao = 23,
  Copia = 24,
  Acessibilidade = 25,
  Disponibilizacao = 26,
  Material = 28,
  Idioma = 29,
  Autor = 30,
  Ano = 31,
  NumeroDePaginas = 32,
  Volume = 33,
  TipoDeAnexo = 34,
  AcessoDocumento = 35,
  Subtitulo = 36,
  Coautor = 37,
  TipoAutoria = 38,
  Editora = 39,
  Assunto = 40,
  Edicao = 41,
  SerieColecao = 42,
  LocalizacaoCDD = 43,
  LocalizacaoPHA = 44,
  NotasGerais = 45,
  ISBN = 46,
  CodigoAntigo = 47,
  CodigoNovo = 48,
}

export const AcervoFieldName: Record<FieldAcervoEnum, string> = {
  [FieldAcervoEnum.Titulo]: 'titulo',
  [FieldAcervoEnum.Tombo]: 'codigo',
  [FieldAcervoEnum.Credito]: 'creditosAutoresIds',
  [FieldAcervoEnum.Localizacao]: 'localizacao',
  [FieldAcervoEnum.Procedencia]: 'procedencia',
  [FieldAcervoEnum.DataAcervo]: 'dataAcervo',
  [FieldAcervoEnum.CopiaDigital]: 'copiaDigital',
  [FieldAcervoEnum.AutorizacaoUsoImagem]: 'permiteUsoImagem',
  [FieldAcervoEnum.EstadoConservacao]: 'conservacaoId',
  [FieldAcervoEnum.Descricao]: 'descricao',
  [FieldAcervoEnum.Quantidade]: 'quantidade',
  [FieldAcervoEnum.DimensaoLargura]: 'largura',
  [FieldAcervoEnum.DimensaoAltura]: 'altura',
  [FieldAcervoEnum.Suporte]: 'suporteId',
  [FieldAcervoEnum.FormatoImagem]: 'formatoId',
  [FieldAcervoEnum.TamanhoArquivo]: 'tamanhoArquivo',
  [FieldAcervoEnum.Cromia]: 'cromiaId',
  [FieldAcervoEnum.Resolucao]: 'resolucao',
  [FieldAcervoEnum.Anexos]: 'arquivos',
  [FieldAcervoEnum.Tecnica]: 'tecnica',
  [FieldAcervoEnum.DimensaoDiametro]: 'diametro',
  [FieldAcervoEnum.DimensaoProfundidade]: 'profundidade',
  [FieldAcervoEnum.Duracao]: 'duracao',
  [FieldAcervoEnum.Copia]: 'copia',
  [FieldAcervoEnum.Acessibilidade]: 'acessibilidade',
  [FieldAcervoEnum.Disponibilizacao]: 'disponibilizacao',
  [FieldAcervoEnum.Material]: 'materialId',
  [FieldAcervoEnum.Idioma]: 'idiomaId',
  [FieldAcervoEnum.Autor]: 'creditosAutoresIds',
  [FieldAcervoEnum.Ano]: 'ano',
  [FieldAcervoEnum.NumeroDePaginas]: 'numeroPagina',
  [FieldAcervoEnum.Volume]: 'volume',
  [FieldAcervoEnum.TipoDeAnexo]: 'tipoAnexo',
  [FieldAcervoEnum.AcessoDocumento]: 'acessoDocumentosIds',
  [FieldAcervoEnum.Subtitulo]: 'subTitulo',
  [FieldAcervoEnum.Coautor]: 'coAutores',
  [FieldAcervoEnum.TipoAutoria]: 'tipoAutoria',
  [FieldAcervoEnum.Editora]: 'editoraId',
  [FieldAcervoEnum.Assunto]: 'assuntosIds',
  [FieldAcervoEnum.Edicao]: 'edicao',
  [FieldAcervoEnum.SerieColecao]: 'serieColecaoId',
  [FieldAcervoEnum.LocalizacaoCDD]: 'localizacaoCDD',
  [FieldAcervoEnum.LocalizacaoPHA]: 'localizacaoPHA',
  [FieldAcervoEnum.NotasGerais]: 'notasGerais',
  [FieldAcervoEnum.ISBN]: 'isbn',
  [FieldAcervoEnum.CodigoAntigo]: 'codigo',
  [FieldAcervoEnum.CodigoNovo]: 'codigoNovo',
};
