export enum ROUTES {
  PRINCIPAL = '/',
  LOGIN = '/login',
  CRIAR_CONTA = '/criar-conta',
  MEUS_DADOS = '/meus-dados',
  REDEFINIR_SENHA = '/redefinir-senha',
  REDEFINIR_SENHA_TOKEN = '/redefinir-senha/:token',
  CREDITO = '/cadastro/credito',
  CREDITO_NOVO = '/cadastro/credito/novo',
  AUTOR = '/cadastro/autor',
  AUTOR_NOVO = '/cadastro/autor/novo',
  EDITORA = '/cadastro/editora',
  EDITORA_NOVO = '/cadastro/editora/novo',
  ASSUNTO = '/cadastro/assunto',
  ASSUNTO_NOVO = '/cadastro/assunto/novo',
  SERIE_COLECAO = '/cadastro/serie-colecao',
  SERIE_COLECAO_NOVO = '/cadastro/serie-colecao/novo',
}
