export const CDEP_BUTTON_ACESSAR = 'CDEP_BUTTON_ACESSAR';
export const CDEP_BUTTON_CRIAR_CONTA = 'CDEP_BUTTON_CRIAR_CONTA';
export const CDEP_BUTTON_CADASTRAR = 'CDEP_BUTTON_CADASTRAR';
export const CDEP_BUTTON_CANCELAR = 'CDEP_BUTTON_CANCELAR';
