export const CDEP_SELECT_UF = 'CDEP_SELECT_UF';
export const CDEP_SELECT_TIPO_USUARIO = 'CDEP_SELECT_TIPO_USUARIO';
export const CDEP_SELECT_TIPO_ACERVO = 'CDEP_SELECT_TIPO_ACERVO';
export const CDEP_SELECT_CREDITO_AUTORIA = 'CDEP_SELECT_CREDITO_AUTORIA';
